/*
 * SQLMapExportJobsWindow.java
 *
 * Created on 04-Apr-2012, 20:21:33
 */
package eesa.gui.windows.db.dataExport.jobs;

import com.whiuk.philip.eesa.db.DatabaseException;
import com.whiuk.philip.eesa.db.dataExport.SQLJobDataExport;
import com.whiuk.philip.eesa.exceptions.InvalidMappingException;
import eesa.gui.help.HelpManager;
import eesa.gui.tables.DataMapTableHeader;
import eesa.gui.tables.DataMapTableHeaderComboCellRenderer;
import eesa.gui.tables.DataMapTableModel;
import eesa.gui.windows.AbstractProcessWindow;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 * Allows the user to create the mapping between SQL fields and EESA data.
 * @author Philip
 */
public class SQLMapExportJobsWindow extends AbstractProcessWindow {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * 
     */
    private final SQLJobDataExport data;

    /** 
     * Creates new form SQLMapExportJobsWindow.
     * @param data 
     */
    public SQLMapExportJobsWindow(final SQLJobDataExport data) {
        this.data = data;
        initComponents();
        HelpManager.addHelpForClassToButton(helpButton, SQLMapExportJobsWindow.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	createFields();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        backButton2.setText("Back");
        backButton2.setEnabled(false);
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        stepsPanel.setBackground(new java.awt.Color(255, 255, 255));

        stepsTitle.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        stepsTitle.setText("Steps");

        step4.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        step4.setText("4. Map Data");

        step3.setFont(new java.awt.Font("Tahoma", 2, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        step3.setText("3. Customise Insertion");

        step2.setFont(new java.awt.Font("Tahoma", 2, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        step2.setText("2. Select Destination");

        step1.setFont(new java.awt.Font("Tahoma", 2, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        step1.setText("1. Select Type");

        javax.swing.GroupLayout stepsPanelLayout = new javax.swing.GroupLayout(stepsPanel);
        stepsPanel.setLayout(stepsPanelLayout);
        stepsPanelLayout.setHorizontalGroup(
            stepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepsTitle)
                    .addComponent(step2)
                    .addComponent(step1)
                    .addComponent(step3)
                    .addComponent(step4))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        stepsPanelLayout.setVerticalGroup(
            stepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heading.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.HEADING_FONT_SIZE)); // NOI18N
        heading.setText("Map Job to Database");

        dataMapTable.setModel(getDataMapTableModel());
        dataMapTable.setTableHeader(getDataMapTableHeader());
        jScrollPane1.setViewportView(dataMapTable);

        javax.swing.GroupLayout layout = 
        		new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stepsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(backButton2)
                    .addComponent(nextButton)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }
    /**
     * 
     */
    private void createFields() {
        helpButton = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        stepsPanel = new javax.swing.JPanel();
        stepsTitle = new javax.swing.JLabel();
        step4 = new javax.swing.JLabel();
        step3 = new javax.swing.JLabel();
        step2 = new javax.swing.JLabel();
        step1 = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataMapTable = new javax.swing.JTable();

	}

	/**
     * 
     * @param evt
     */
    private void helpButtonActionPerformed(final java.awt.event.ActionEvent evt) {
}
    /**
     * 
     * @param evt 
     */
    private void backButton2ActionPerformed(final java.awt.event.ActionEvent evt) {
        try {
            updateData();
        } catch (InvalidMappingException ex) {            
            Logger.getLogger(SQLMapExportJobsWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Mapping Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);            
        }
        new SQLInsertionExportJobsWindow(data).setVisible(true);
}
    /**
     * 
     * @param evt
     */
    private void finishButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        try {
            exportData();
            dispose();
        } catch (DatabaseException ex) {            
            Logger.getLogger(SQLMapExportJobsWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Export Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        } catch (InvalidMappingException ex) {
            Logger.getLogger(SQLMapExportJobsWindow.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(this, "Mapping Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);            
        }
}
    /**
     * 
     * @param evt
     */
    private void cancelButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
}
    /**
     * 
     * @param evt
     */
    private void nextButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        //Do Nothing
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
	/**
	 * 
	 */
    private javax.swing.JButton backButton2;
	/**
	 * 
	 */
    private javax.swing.JButton cancelButton;
	/**
	 * 
	 */
    private javax.swing.JTable dataMapTable;
	/**
	 * 
	 */
    private javax.swing.JButton finishButton;
	/**
	 * 
	 */
    private javax.swing.JLabel heading;
	/**
	 * 
	 */
    private javax.swing.JButton helpButton;
	/**
	 * 
	 */
    private javax.swing.JScrollPane jScrollPane1;
	/**
	 * 
	 */
    private javax.swing.JButton nextButton;
	/**
	 * 
	 */
    private javax.swing.JLabel step1;
	/**
	 * 
	 */
    private javax.swing.JLabel step2;
	/**
	 * 
	 */
    private javax.swing.JLabel step3;
	/**
	 * 
	 */
    private javax.swing.JLabel step4;
	/**
	 * 
	 */
    private javax.swing.JPanel stepsPanel;
	/**
	 * 
	 */
    private javax.swing.JLabel stepsTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @throws InvalidMappingException 
     */
    private void updateData() throws InvalidMappingException {
        int[] columnKeys = new int[data.getChoices().size()];
        boolean[] parameters = new boolean[data.getChoices().size()];
        for (int c = 0; c < dataMapTable.getModel().getColumnCount(); c++) {
            String colName = dataMapTable.getModel().getColumnName(c);
            List<String> choices = data.getChoices();
            if (choices.contains(colName)) {
                parameters[choices.indexOf(colName)] = true;
                columnKeys[choices.indexOf(colName)] = c;
            }
            data.setParameters(parameters);
            data.setColumnKeys(columnKeys);            
        }
    }

    /**
     * 
     * @return
     */
    private TableModel getDataMapTableModel() {
        return new DataMapTableModel(data.getMappingData(), data.getColumns());
    }

    /**
     * 
     * @return
     */
    private JTableHeader getDataMapTableHeader() {
        return new DataMapTableHeader(dataMapTable.getColumnModel(),
        		getDataMapComboBoxes(), getDataMapRenderers());
    }
    /**
     * 
     * @return
     */
    private JComboBox<String>[] getDataMapComboBoxes() {
        int columns = data.getNumColumns();
        @SuppressWarnings("unchecked")
		JComboBox<String>[] comboBoxes = new JComboBox[columns];
        for (int c = 0; c < columns; c++) {
            comboBoxes[c] = new JComboBox<String>(data.getChoicesForIndex(c));
        }
        return comboBoxes;
    }
    /**
     * 
     * @throws InvalidMappingException 
     */
    private void exportData() throws InvalidMappingException, DatabaseException {
        updateData();
        data.performExport();
    }
    /**
     * 
     * @return 
     */
    private DataMapTableHeaderComboCellRenderer[] getDataMapRenderers() {
        int columns = data.getNumColumns();
        DataMapTableHeaderComboCellRenderer[] renderers = new DataMapTableHeaderComboCellRenderer[columns];
        for (int c = 0; c < columns; c++) {
            renderers[c] = new DataMapTableHeaderComboCellRenderer(data.getChoicesForIndex(c));
        }
        return renderers;
    }
}
