package eesa.gui.windows.csv.dataExport.jobs;

/*
 * CSVExportJobsWindow.java
 *
 * Created on 02-Apr-2012, 11:31:39
 */
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import com.whiuk.philip.eesa.csv.dataExport.CSVJobDataExport;
import eesa.gui.csv.CSVFileFilter;
import eesa.gui.help.HelpManager;
import eesa.gui.windows.dataExport.jobs.AbstractExportJobsWindow;
import eesa.gui.windows.dataExport.jobs.ExportJobsWindow;
import javax.swing.JFileChooser;

/**
 * Enables the user to select the destination file and the delimiter.
 * @author Philip
 */
public class CSVExportJobsWindow extends AbstractExportJobsWindow {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     * 
     */
    private CSVJobDataExport data;
    /** Creates new form CSVExportJobsWindow.
     * @param d 
     */
    public CSVExportJobsWindow(final CSVJobDataExport d) {
        this.data = d;
        initComponents();
        HelpManager.addHelpForClassToButton(helpButton, CSVExportJobsWindow.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	createFields();
    	setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        stepsPanel.setBackground(new java.awt.Color(255, 255, 255));
        stepsTitle.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.FONT_SIZE)); // NOI18N
        stepsTitle.setText("Steps");
        step1.setFont(new java.awt.Font("Tahoma", 2, eesa.gui.Application.FONT_SIZE)); // NOI18N
        step1.setText("1. Select Type");
        step2.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.FONT_SIZE)); // NOI18N
        step2.setText("2. Select Destination");
        step3.setText("3. Customise Output");
        step4.setText("4. View Exported Data");
        GroupLayout stepsPanelLayout = new GroupLayout(stepsPanel);
        stepsPanel.setLayout(stepsPanelLayout);
        stepsPanelLayout.setHorizontalGroup(
            stepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(stepsTitle)
                    .addComponent(step2)
                    .addComponent(step3)
                    .addComponent(step4)
                    .addComponent(step1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        stepsPanelLayout.setVerticalGroup(
            stepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepsTitle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step4)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        heading.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.HEADING_FONT_SIZE)); // NOI18N
        heading.setText("Select CSV File Destination");
        fileSourceLabel.setText("File Destination:");
        delimeterLabel.setText("Delimeter:");
        delimeterField.setText(",");
        fileBrowseButton.setText("Browse");
        fileBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                fileBrowseButtonActionPerformed(evt);
            }
        });
        backButton.setText("Back");
        backButton.setEnabled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        buildLayout();
        pack();
    }
    /**
     * 
     */
    private void buildLayout() {
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stepsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(heading, GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(eesa.gui.Application.GAP, eesa.gui.Application.GAP, eesa.gui.Application.GAP)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(fileSourceLabel)
                            .addComponent(delimeterLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(delimeterField, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileSourceField, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileBrowseButton)
                .addGap(41, 41, 41))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stepsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(fileSourceLabel)
                    .addComponent(fileSourceField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileBrowseButton))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(delimeterLabel)
                    .addComponent(delimeterField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(backButton)
                    .addComponent(nextButton)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
	}

	/**
     * 
     */
    private void createFields() {
        stepsPanel = new JPanel();
        stepsTitle = new JLabel();
        step1 = new JLabel();
        step2 = new JLabel();
        step3 = new JLabel();
        step4 = new JLabel();
        heading = new JLabel();
        fileSourceLabel = new JLabel();
        delimeterLabel = new JLabel();
        delimeterField = new JTextField();
        fileSourceField = new JTextField();
        fileBrowseButton = new JButton();
        backButton = new JButton();
        nextButton = new JButton();
        finishButton = new JButton();
        cancelButton = new JButton();
        helpButton = new JButton();

	}

	/**
     * 
     * @param evt
     */
    private void fileBrowseButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        JFileChooser c = new JFileChooser();
        CSVFileFilter filter = new CSVFileFilter();
        c.setFileFilter(filter);
        int returnVal = c.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileSourceField.setText(c.getSelectedFile().getAbsolutePath());
        }
        updateData();
}

    /**
     * 
     * @param evt
     */
    private void backButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        updateData();
        new ExportJobsWindow(data).setVisible(true);
        dispose();
}

    /**
     * 
     * @param evt
     */
    private void nextButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        updateData();
        new CSVMapExportJobsWindow(data).setVisible(true);
        dispose();
}

    /**
     * 
     * @param evt
     */
    private void finishButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        // Do Nothing
}

    /**
     * 
     * @param evt
     */
    private void cancelButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
}

    /**
     * 
     * @param evt
     */
    private void helpButtonActionPerformed(final java.awt.event.ActionEvent evt) {
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * 
     */
    private JButton backButton;
    /**
     * 
     */
    private JButton cancelButton;
    /**
     * 
     */
    private JTextField delimeterField;
    /**
     * 
     */
    private JLabel delimeterLabel;
    /**
     * 
     */
    private JButton fileBrowseButton;
    /**
     * 
     */
    private JTextField fileSourceField;
    /**
     * 
     */
    private JLabel fileSourceLabel;
    /**
     * 
     */
    private JButton finishButton;
    /**
     * 
     */
    private JLabel heading;
    /**
     * 
     */
    private JButton helpButton;
    /**
     * 
     */
    private JButton nextButton;
    /**
     * 
     */
    private JLabel step1;
    /**
     * 
     */
    private JLabel step2;
    /**
     * 
     */
    private JLabel step3;
    /**
     * 
     */
    private JLabel step4;
    /**
     * 
     */
    private JPanel stepsPanel;
    /**
     * 
     */
    private JLabel stepsTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    private void updateData() {
        data.setDelimeter(delimeterField.getText());
        data.setFile(fileSourceField.getText());
    }
}
