package com.whiuk.philip.eesa.exceptions;

/**
 * The superclass for all unchecked exceptions generated by EESA.
 * @author Philip Whitehouse
 *
 */
public class EESARuntimeException extends RuntimeException {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 * @param msg Message
	 */
	public EESARuntimeException(final String msg) {
		super(msg);
	}
	/**
	 * 
	 */
	public EESARuntimeException() {
		super();
	}
	/**
	 * 
	 * @param cause Cause of exception
	 */
	public EESARuntimeException(final Throwable cause) {
		super(cause);
	}

}
