/*
 * AddDatabaseSortWindow.java
 *
 * Created on 05-Apr-2012, 10:45:40
 */
package eesa.gui.windows.db;

import eesa.db.Field;
import eesa.db.OrderByClause;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 * Provides a window to add a database data sort.
 * @author Philip
 */
public class AddDatabaseSortWindow extends JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
    private DatabaseWindow parent;
    /** 
     * Creates new form AddDatabaseSortWindow.
     * @param window parent
     */
    public AddDatabaseSortWindow(final DatabaseWindow window) {
        parent = window;
        initComponents();
    }
    /**
     * 
     * @return fields combo-box model
     */
    private ComboBoxModel<Field> getFields() {
        return new DefaultComboBoxModel<Field>(parent.getFields());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        heading = new JLabel();
        fieldLabel = new JLabel();
        fieldComboBox = new JComboBox<Field>();
        sortOrderLabel = new JLabel();
        sortOrderComboBox = new JComboBox<String>();
        addButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        heading.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.HEADING_FONT_SIZE)); // NOI18N
        heading.setText("Add Condition");

        fieldLabel.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.FONT_SIZE)); // NOI18N
        fieldLabel.setText("Field");

        fieldComboBox.setModel(getFields());

        sortOrderLabel.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.FONT_SIZE)); // NOI18N
        sortOrderLabel.setText("Sort Order");

        sortOrderComboBox.setModel(new DefaultComboBoxModel<String>(
        		new String[] { "Ascending", "Descending" }));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(heading, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(fieldLabel, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortOrderLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(sortOrderComboBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(fieldComboBox, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addButton, GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLabel)
                    .addComponent(fieldComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(sortOrderLabel)
                    .addComponent(sortOrderComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }
    /**
     * 
     * @param evt
     */
    private void addButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        Field f = (Field) fieldComboBox.getSelectedItem();
        int ordering = sortOrderComboBox.getSelectedIndex();
        if (f != null && ordering != -1) {
            OrderByClause orderBy = parent.getDatabase().orderBy(f, ordering);
            parent.addSort(orderBy);
            dispose();
        }
}
    /**
     * 
     * @param evt
     */
    private void cancelButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        this.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * 
     */
    private JButton addButton;
    /**
     * 
     */
    private JButton cancelButton;
    /**
     * 
     */
    private JComboBox<Field> fieldComboBox;
    /**
     * 
     */
    private JLabel fieldLabel;
    /**
     * 
     */
    private JLabel heading;
    /**
     * 
     */
    private JComboBox<String> sortOrderComboBox;
    /**
     * 
     */
    private JLabel sortOrderLabel;
    // End of variables declaration//GEN-END:variables
}
