/*
 * AddDatabaseTableWindow.java
 *
 * Created on 05-Apr-2012, 10:45:25
 */
package eesa.gui.windows.db;

import com.whiuk.philip.eesa.db.DatabaseException;
import com.whiuk.philip.eesa.db.DatabaseTable;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Provides a window to add a database table.
 * @author Philip
 */
public class AddDatabaseTableWindow extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     * 
     */
    private DatabaseWindow parent;
    /**
     * Creates new form AddDatabaseTableWindow.
     * @param p parent 
     */
    public AddDatabaseTableWindow(final DatabaseWindow p) {
        this.parent = p;
        initComponents();
    }
    /**
     * 
     * @return
     */
    private ComboBoxModel<DatabaseTable> getTables() {
    	DatabaseTable[] tables = new DatabaseTable[]{};
        try {
            tables = parent.getDatabase().getTables();
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(this, parent.getDatabaseConnector() + " Error: Unable to retrieve tables", "Database Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AddDatabaseFieldWindow.class.getName()).log(Level.INFO, "SQL Exception retrieving tables", ex);
        }
        return new DefaultComboBoxModel<DatabaseTable>(tables);
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        heading = new javax.swing.JLabel();
        tableComboBox = new javax.swing.JComboBox<DatabaseTable>();
        tableLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Table");

        heading.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.HEADING_FONT_SIZE)); // NOI18N
        heading.setText("Add Table");

        tableComboBox.setModel(getTables());

        tableLabel.setText("Table");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tableComboBox, 0, 164, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableLabel)
                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }
    /**
     * 
     * @param evt
     */
    private void cancelButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        this.dispose();
    }
    /**
     * 
     * @param evt
     */
    private void addButtonActionPerformed(final java.awt.event.ActionEvent evt) {
        if (tableComboBox.getSelectedItem() != null) {
            parent.addTable((DatabaseTable) tableComboBox.getSelectedItem());
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * 
     */
    private javax.swing.JButton addButton;
    /**
     * 
     */
    private javax.swing.JButton cancelButton;
    /**
     * 
     */
    private javax.swing.JLabel heading;
    /**
     * 
     */
    private javax.swing.JComboBox<DatabaseTable> tableComboBox;
    /**
     * 
     */
    private javax.swing.JLabel tableLabel;
    // End of variables declaration//GEN-END:variables
}
