package eesa.gui.windows.imageExport.speed;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import eesa.gui.charts.Charts;
import eesa.gui.charts.Charts.SplitType;
import eesa.gui.windows.AbstractProcessWindow;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 * Allows the user to determine whether and how to split the data.
 * @author Philip
 */
public class SplitExportSpeedChartWindow extends AbstractProcessWindow {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Export data.
	 */
    private final SpeedImageExport data;

    /**
     * Creates new form SplitExportSpeedChartWindow.
     * @param e data
     */
    public SplitExportSpeedChartWindow(final SpeedImageExport e) {
        this.data = e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        splitTypeDescriptionTextArea = new JTextArea();
        nextButton = new JButton();
        backButton = new JButton();
        stepsPanel = new JPanel();
        stepsTitle = new JLabel();
        step1 = new JLabel();
        step2 = new JLabel();
        jLabel1 = new JLabel();
        cancelButton = new JButton();
        splitTypeComboBox = new JComboBox<Charts.SplitType>();
        helpButton = new JButton();
        jobAssignmentAlgorithmLabel = new JLabel();
        finishButton = new JButton();
        heading = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        splitTypeDescriptionTextArea.setColumns(20);
        splitTypeDescriptionTextArea.setEditable(false);
        splitTypeDescriptionTextArea.setFont(new Font("Arial", 0, eesa.gui.Application.FONT_SIZE));
        splitTypeDescriptionTextArea.setLineWrap(true);
        splitTypeDescriptionTextArea.setRows(5);
        splitTypeDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(splitTypeDescriptionTextArea);

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.setEnabled(false);
        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        stepsPanel.setBackground(new java.awt.Color(255, 255, 255));

        stepsTitle.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        stepsTitle.setText("Steps");

        step1.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.STEP_FONT_SIZE)); // NOI18N
        step1.setText("1. Select Sources");

        step2.setText("2. Select Chart Split Type");

        jLabel1.setText("3. Select Destination");

        buildStepsPanelLayout();

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        splitTypeComboBox.setModel(getSplitTypesComboBoxModel());
        splitTypeComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                splitTypeComboBoxActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        jobAssignmentAlgorithmLabel.setText("Type");

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Tahoma", 1, eesa.gui.Application.HEADING_FONT_SIZE)); // NOI18N
        heading.setText("Select Chart Split Type");

        buildLayout();

        pack();
    }
    /**
     * Layout builder.
     */
    private void buildLayout() {
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stepsPanel,
                		GroupLayout.PREFERRED_SIZE,
                		GroupLayout.DEFAULT_SIZE,
                		GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heading)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(
                        		GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jobAssignmentAlgorithmLabel)
                                .addGap(18, 18, 18)
                                .addComponent(splitTypeComboBox, 0,
                                		GroupLayout.DEFAULT_SIZE,
                                		Short.MAX_VALUE))
                            .addComponent(jScrollPane1,
                            		GroupLayout.DEFAULT_SIZE,
                            		364, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(GroupLayout.Alignment.TRAILING,
            		layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.LEADING)
                    .addComponent(stepsPanel,
                    		GroupLayout.PREFERRED_SIZE,
                    		GroupLayout.DEFAULT_SIZE,
                    		GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(
                        		GroupLayout.Alignment.BASELINE)
                            .addComponent(jobAssignmentAlgorithmLabel)
                            .addComponent(splitTypeComboBox,
                            		GroupLayout.PREFERRED_SIZE,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1,
                        		GroupLayout.PREFERRED_SIZE,
                        		106,
                        		GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(backButton)
                    .addComponent(nextButton)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }
    /**
     * Layout builder.
     */
    private void buildStepsPanelLayout() {
        GroupLayout stepsPanelLayout = new GroupLayout(stepsPanel);
        stepsPanel.setLayout(stepsPanelLayout);
        stepsPanelLayout.setHorizontalGroup(
            stepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stepsPanelLayout.createParallelGroup(
                		GroupLayout.Alignment.LEADING)
                    .addComponent(stepsTitle)
                    .addComponent(step2)
                    .addComponent(step1)
                    .addComponent(jLabel1))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepsPanelLayout.setVerticalGroup(
            stepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(stepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepsTitle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );    	
    }
    /**
     * Reacts to next button.
     * @param evt Click event
     */
    private void nextButtonActionPerformed(final ActionEvent evt) {
        updateData();
        new DestinationExportSpeedChartWindow(data).setVisible(true);
    }

    /**
     * Reacts to back button.
     * @param evt Click event
     */
    private void backButtonActionPerformed(final ActionEvent evt) {
    	//GEN-FIRST:event_backButtonActionPerformed
        // Do Nothing
    }

    /**
     * Reacts to cancel button.
     * @param evt Click event
     */
    private void cancelButtonActionPerformed(final ActionEvent evt) {
    	//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }

    /**
     * Reacts to split type change.
     * @param evt Event
     */
    private void splitTypeComboBoxActionPerformed(final ActionEvent evt) {
    	//GEN-FIRST:event_splitTypeComboBoxActionPerformed
        Charts.SplitType selected = 
        		(SplitType) splitTypeComboBox.getSelectedItem();
        splitTypeDescriptionTextArea.setText(selected.getDescription());
        splitTypeDescriptionTextArea.setCaretPosition(0);
    }

    /**
     * Reacts to help button.
     * @param evt Click event
     */
    private void helpButtonActionPerformed(final ActionEvent evt) {
    	//GEN-FIRST:event_helpButtonActionPerformed

   }

    /**
     * Reacts to finish button.
     * @param evt Click event
     */
    private void finishButtonActionPerformed(final ActionEvent evt) {
    	//GEN-FIRST:event_finishButtonActionPerformed
        // Do Nothing
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Back button.
     */
    private JButton backButton;
    /**
     * Cancel button.
     */
    private JButton cancelButton;
    /**
     * Finish button.
     */
    private JButton finishButton;
    /**
     * Heading.
     */
    private JLabel heading;
    /**
     * Help button.
     */
    private JButton helpButton;
    /**
     * Label.
     */
    private JLabel jLabel1;
    /**
     * Scroll pane.
     */
    private JScrollPane jScrollPane1;
    /**
     * Job Assignment Algorithm label.
     */
    private JLabel jobAssignmentAlgorithmLabel;
    /**
     * Next button.
     */
    private JButton nextButton;
    /**
     * Split type box.
     */
    private JComboBox<Charts.SplitType> splitTypeComboBox;
    /**
     * Description.
     */
    private JTextArea splitTypeDescriptionTextArea;
    /**
     * Step 1.
     */
    private JLabel step1;
    /**
     * Step 2.
     */
    private JLabel step2;
    /**
     * Steps.
     */
    private JPanel stepsPanel;
    /**
     * Steps title.
     */
    private JLabel stepsTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    private void updateData() {
        data.setSplitType((Charts.SplitType) 
        		splitTypeComboBox.getSelectedItem());
    }

    /**
     * 
     * @return combo-box model
     */
    private ComboBoxModel<Charts.SplitType> getSplitTypesComboBoxModel() {
        return new DefaultComboBoxModel<Charts.SplitType>(
        		new Charts.SplitType[]{
		            Charts.SplitType.SINGLE,
		            Charts.SplitType.BY_TEST,
		            Charts.SplitType.BY_PROCESSOR,
		            Charts.SplitType.BY_BOTH});
    }
}
