package eesa.exceptions;

/**
 * The superclass for all checked exceptions generated by EESA. 
 * @author Philip
 */
public class EESAException extends Exception {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @param msg Message
     * @param cause Underlying exception
     */
    public EESAException(final String msg, final Throwable cause) {
        super(msg, cause);
    }
    /**
     * 
     * @param cause 
     */
    public EESAException(final Throwable cause) {
        super(cause);
    }    
    /**
     * 
     * @param msg Message
     */
    public EESAException(final String msg) {
        super(msg);
    }
    /**
     * 
     */
    public EESAException() {
        super();
    }
}
