/*
 * AlterJobWindow.java
 *
 * Created on 03-Apr-2012, 21:47:22
 */
package eesa.gui.windows;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

import com.whiuk.philip.eesa.core.Job;
import com.whiuk.philip.eesa.exceptions.TimeIntervalException;
import eesa.gui.help.HelpManager;
import javax.swing.JOptionPane;

/**
 * Allows users to alter a job.
 * @author Philip
 */
public class AlterJobWindow extends JFrame {
	/**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    /**
     * The job to alter.
     */
    private final Job job;
    /** Creates new form AlterJobWindow.
     * @param j 
     */
    public AlterJobWindow(final Job j) {
        job = j;
        initComponents();
        HelpManager.addHelpForClassToButton(helpButton, AlterJobWindow.class);
    }

    /**
     * This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
    	createFields();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        releaseLabel.setText("Release Time");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1,
        		eesa.gui.Application.HEADING_FONT_SIZE));
        jLabel1.setText("Alter Job");
        weightLabel.setText("Weight");
        lengthResultLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        lengthResultLabel.setText("0");
        deadlineLabel.setText("Deadline Time");
        lengthLabel.setText("Length");
        densityResultLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        densityResultLabel.setText("0");
        densityLabel.setText("Density");
        releaseField.setHorizontalAlignment(JTextField.RIGHT);
        releaseField.setText("0");
        deadlineField.setHorizontalAlignment(JTextField.RIGHT);
        deadlineField.setText("0");
        deadlineField.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                deadlineFieldActionPerformed(evt);
            }
        });
        weightField.setHorizontalAlignment(JTextField.RIGHT);
        weightField.setText("0");
        submitButton.setText("Submit");
        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        helpButton.setText("Help");
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(
                        		GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deadlineLabel,
                            		GroupLayout.Alignment.LEADING,
                            		GroupLayout.DEFAULT_SIZE, 96,
                            		Short.MAX_VALUE)
                            .addComponent(releaseLabel,
                            		GroupLayout.Alignment.LEADING,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.DEFAULT_SIZE,
                            		Short.MAX_VALUE)
                            .addComponent(weightLabel,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.DEFAULT_SIZE,
                            		Short.MAX_VALUE)
                            .addComponent(densityLabel,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.DEFAULT_SIZE,
                            		Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(
                        		GroupLayout.Alignment.LEADING)
                            .addComponent(densityResultLabel,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deadlineField)
                            .addComponent(weightField)
                            .addComponent(lengthResultLabel,
                            		GroupLayout.DEFAULT_SIZE,
                            		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(releaseField,
                            		GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(
                        		GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lengthLabel,
                            		GroupLayout.PREFERRED_SIZE, 96,
                            		GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addPreferredGap(
                                		LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addPreferredGap(
                                		LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helpButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(releaseLabel)
                    .addComponent(releaseField,
                    		GroupLayout.PREFERRED_SIZE,
                    		GroupLayout.DEFAULT_SIZE,
                    		GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineLabel)
                    .addComponent(deadlineField, GroupLayout.PREFERRED_SIZE,
                    		GroupLayout.DEFAULT_SIZE,
                    		GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthResultLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(weightField,
                    		GroupLayout.PREFERRED_SIZE,
                    		GroupLayout.DEFAULT_SIZE,
                    		GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(densityLabel)
                    .addComponent(densityResultLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(
                		GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton)
                    .addComponent(helpButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }
    /**
     * 
     */
    private void createFields() {
        releaseLabel = new JLabel();
        jLabel1 = new JLabel();
        weightLabel = new JLabel();
        lengthResultLabel = new JLabel();
        deadlineLabel = new JLabel();
        lengthLabel = new JLabel();
        densityResultLabel = new JLabel();
        densityLabel = new JLabel();
        releaseField = new JTextField();
        deadlineField = new JTextField();
        weightField = new JTextField();
        submitButton = new JButton();
        cancelButton = new JButton();
        helpButton = new JButton();
	}

	/**
     * 
     * @param evt event
     */
    private void deadlineFieldActionPerformed(final ActionEvent evt) {

    }
    /**
     * 
     * @param evt event
     */
    private void submitButtonActionPerformed(final ActionEvent evt) {
        try {
            job.setReleaseTime(Float.parseFloat(this.releaseField.getText()));
            job.setDeadlineTime(Float.parseFloat(this.deadlineField.getText()));
            job.setWeight(Float.parseFloat(this.weightField.getText()));
            setVisible(false);
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error",
            		"One of the fields is not a floating point number",
            		JOptionPane.ERROR_MESSAGE);
        } catch (TimeIntervalException ex) {
            JOptionPane.showMessageDialog(this, "Error",
            		ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * 
     * @param evt event
     */
    private void cancelButtonActionPerformed(final ActionEvent evt) {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * 
     */
    private JButton cancelButton;
    /**
     * 
     */
    private JTextField deadlineField;
    /**
     * 
     */
    private JLabel deadlineLabel;
    /**
     * 
     */
    private JLabel densityLabel;
    /**
     * 
     */
    private JLabel densityResultLabel;
    /**
     * 
     */
    private JButton helpButton;
    /**
     * 
     */
    private JLabel jLabel1;
    /**
     * 
     */
    private JLabel lengthLabel;
    /**
     * 
     */
    private JLabel lengthResultLabel;
    /**
     * 
     */
    private JTextField releaseField;
    /**
     * 
     */
    private JLabel releaseLabel;
    /**
     * 
     */
    private JButton submitButton;
    /**
     * 
     */
    private JTextField weightField;
    /**
     * 
     */
    private JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
